<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="renderer" content="webkit">
    <title>租赁商城 -- 消息提示</title>
    <style type="text/css">
    div,p{
        margin: 0;
        padding: 0;
    }
    .no_pages{
        width: 750px;
        margin: 182px auto 0;
    }
    .no_pages_pic{
        float: left;
        width: 323px;
        height: 255px;
        background: url(http://static.wujigang.cn/bmmyouStatic/cuoheStatic/common/images/background/20170730_02.jpg) no-repeat;
    }
    .no_pages_txt{
        float: right;
        font-size: 18px;
        line-height: 4em;
        margin-top: 70px;
    }
    .no_pages_txt span{
        font-size: 36px;
        color: #333;
    }
    .no_pages_txt em{
        color: #306ccb;
        font-style: normal;
    }
    .no_pages_txt a{
        color: #306ccb;
    }
    </style>
</head>
<body>
<div class="no_pages clearfix">
    <div class="no_pages_pic"></div>
    <p class="no_pages_txt">
        <span><?php echo $message;?></span><br />
        <?php if ($second > 0) :?>
        <em><?php echo $second;?></em>秒后自动跳转，不想等待，
        <?php endif;?>
        请点<a href="<?php echo $jumpUrl;?>">击跳转至这里</a>
    </p>
</div>
<script type="text/javascript">
(function skipTime() {
    var oEm = document.getElementsByClassName("no_pages_txt")[0].getElementsByTagName("em");
    if (oEm.length > 0) {
        oEm = oEm[0];
        var itime=parseInt(oEm.innerHTML);
        if (itime!==0) {
            oEm.innerHTML=itime-1;
            setTimeout(function (argument) {
                skipTime();
            },1000);
        }else{
            location.href="<?php echo $jumpUrl;?>";
        }
    }
})();
</script>
</body>
</html>